version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-llm
    ports:
      - "${REDIS_PORT:-6379}:6379"  # Redis port
      - "8001:8001"  # RedisInsight Web UI
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
      - REDISEARCH_ARGS=MAXSEARCHRESULTS 10000
    volumes:
      - redis_data:/data
    restart: unless-stopped
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis_data:
    name: redis_data 